### ISSUE TITLE
what's fortran

### ISSUE THREAD

**Issue by AyeayeTheAwesome** [PlanetCentral/FortranRunner#2]
is it like a transformers character like bumblebee or optimus prime?

**Comment by PlanetCentral** [comment]
Great question! 

Fortran (aka Formula Translator) is a programming language mainly for science, engineering, and finance/math. It became pretty popular with scientists, engineers, and others for math calculations, modeling scientific phenomena, and processing large datasets. Because of its good performance and number of libraries, its still popular in areas like physics, chem, fluid dynamics even, and finance (COBOL is the go-to though).

**Comment by PlanetCentral** [comment]
and you know I dont think its like bumblebee or optimus prime, but that would be pretty cool. someone needs to make a picture of that!
